[config]
ghidra_home = "/opt/ghidra_11.3.2_PUBLIC"
eval_type = "Subset Evaluation" # "Dataset Evaluation", "Subset Evaluation"
datasets = ["Loadstar"]
dump_json = true
result_path = "./eval_results"
evaluator = ["NSDA", "Ghidra"]

[dataset.loadstar]
path = "./Loadstar"
loader = "LoadstarDataLoader"
subset = ["acos_fbd.app"]

[evaluator.nsda]
iteration_limit = 5
epoches_limit = 500
