[config]
ghidra_home = "/opt/ghidra_11.3.2_PUBLIC"
eval_type = "Subset Evaluation"
datasets = ["Loadstar"]
dump_json = true
result_path = "./eval_results"
# evaluator = ["Loadstar"]
evaluator = ["Ghidra", "NSDA"]

[dataset.loadstar]
path = "./Datasets/Loadstar"
loader = "LoadstarDataLoader"
subset = ["5.22.152.8.PRG"]

[evaluator.nsda]
iteration_limit = 5
epoches_limit = 500

[evaluator.loadstar]
loadstar_home = "./Datasets/Loadstar"
weights_path = "new_weights.weights.h5"
tokenizer_path = "utils/tokenizer.pkl"
maxlen = 100
batch_size = 128
vocab_size = 651997
embedding_dim = 128
lstm_units = 64
