[config]
ghidra_home = "/opt/ghidra_11.3.2_PUBLIC"
# eval_type = "Subset Evaluation"
eval_type = "Dataset Evaluation"
# datasets = ["Loadstar"]
# datasets = ["Loadstar", "arm32_coreutils"]
# datasets = ["arm32_coreutils"]
datasets = ["mips_coreutils"]
dump_json = true
dump_error_list = false
result_path = "./eval_results"
# evaluator = ["Loadstar"]
evaluator = ["NSDA", "Ghidra"]
# evaluator = ["Ghidra", "NSDA", "Loadstar", "ProbNSDA"]
# evaluator = ["Ghidra", "NSDA", "ProbNSDA"]
# evaluator = ["Ghidra"]
# evaluator = ["ProbNSDA"]

log_file = "stderr"
log_level = "info"

[dataset.loadstar]
path = "./Datasets/Loadstar"
loader = "LoadstarDataLoader"
subset = ["acos_fbd.app"]
base = 0x0

[dataset.arm32_coreutils]
path = "./Datasets/coreutils-arm"
loader = "ARMCoreutilsDataLoader"
subset = ["base64"]
base = 0x10000
language = "ARM:LE:32:v5"

[dataset.mips_coreutils]
path = "./Datasets/coreutils-mips32"
loader = "MIPSCoreutilsDataLoader"
subset = ["base64"]
base = 0x400000
language = "MIPS:BE:32:default"

[evaluator.nsda]
iteration_limit = 5
epoches_limit = 500
keep_ghidra_prj = false
keep_ghidra_prj_path = "./saved_ghidra_prjs"


[evaluator.probnsda]
iteration_limit = 1
epoches_limit = 2000
keep_ghidra_prj = false
keep_ghidra_prj_path = "./saved_ghidra_prjs"
language = "MIPS:BE:32:default"

[evaluator.ghidra]
keep_ghidra_prj = false
keep_ghidra_prj_path = "./saved_ghidra_prjs"
language = "MIPS:BE:32:default"
# dump_blocks_path = "./blocks.txt" # Debug use

[evaluator.loadstar]
loadstar_home = "./Datasets/Loadstar"
weights_path = "new_weights.weights.h5"
tokenizer_path = "utils/tokenizer.pkl"
maxlen = 100
batch_size = 128
vocab_size = 651997
embedding_dim = 128
lstm_units = 64
