[config]
ghidra_home = "/opt/ghidra_12.0.4_PUBLIC"
eval_type = "Dataset Evaluation"
dump_json = true
dump_error_list = true
result_path = "./eval_results"
log_file = "./nsda_eval.log"
log_level = "info"

datasets = ["openssl_x64"]
evaluator = [ "nsda", "nsdaworules", "probnsda", "ghidra", "ddisasm",]

[dataset.loadstar]
path = "./Datasets/Loadstar"
loader = "LoadstarDataLoader"
base = 0
language = "ARM:LE:32:v5"

[dataset.arm32_coreutils]
path = "./Datasets/coreutils-arm"
loader = "ARMCoreutilsDataLoader"
base = 65536
language = "ARM:LE:32:v5"

[dataset.arm32_coreutils_llvm]
path = "./Datasets/coreutils-arm-llvm"
loader = "ARMCoreutilsDataLoader"
base = 0
language = "ARM:LE:32:v5"
llvm_arm32 = true

[dataset.mips_coreutils]
path = "./Datasets/coreutils-mips"
loader = "MIPSCoreutilsDataLoader"
base = 4194304
language = "MIPS:BE:32:default"

[dataset.mips_coreutils_llvm]
path = "./Datasets/coreutils-mips-llvm"
loader = "MIPSCoreutilsDataLoader"
base = 0
language = "MIPS:BE:32:default"
llvm_arm32 = true

[dataset.openssl_x64]
path = "./Datasets/OpenSSL-x64"
loader = "OpensslDataLoader"
base = 0x400000
language = "x86:LE:64:default"

[dataset.chromium_pe_x64]
path = "./Datasets/chromium-PE-x64"
loader = "ChromiumDataLoader"
base = 0x0
language = "x86:LE:64:default"

[evaluator.nsda]
iteration_limit = 5
epoches_limit = 500
keep_ghidra_prj = false
keep_ghidra_prj_path = "./saved_ghidra_prjs"

[evaluator.nsdaworules]
iteration_limit = 5
epoches_limit = 500
keep_ghidra_prj = false
keep_ghidra_prj_path = "./saved_ghidra_prjs"

[evaluator.probnsda]
iteration_limit = 1
epoches_limit = 2000
keep_ghidra_prj = false
keep_ghidra_prj_path = "./saved_ghidra_prjs"

[evaluator.ghidra]
keep_ghidra_prj = false
keep_ghidra_prj_path = "./saved_ghidra_prjs"

[evaluator.loadstar]
loadstar_home = "./Datasets/Loadstar"
weights_path = "new_weights.weights.h5"
tokenizer_path = "utils/tokenizer.pkl"
maxlen = 100
batch_size = 128
vocab_size = 651997
embedding_dim = 128
lstm_units = 64

[evaluator.ddisasm]
