[config]
ghidra_home = "/opt/ghidra_11.3.2_PUBLIC"
eval_type = "Dataset Evaluation"
dump_json = true
dump_error_list = false
result_path = "./eval_results"
log_file = "./logs/all.log"
log_level = "info"

datasets = ["loadstar", "arm32_coreutils", "arm32_coreutils_llvm", "mips_coreutils", "mips_coreutils_llvm", "openssl_x64"]
evaluator = [ "nsda", "nsdaworules", "probnsda", "ghidra", "ddisasm", "loadstar"]

[dataset.loadstar]
path = "./Datasets/Loadstar"
loader = "LoadstarDataLoader"
base = 0
language = "ARM:LE:32:v5"
subset = ["5.22.152.8.PRG", "3.PRG", "acos_fbd.app"]

[dataset.arm32_coreutils]
path = "./Datasets/coreutils/arm32-gcc"
loader = "ARMCoreutilsDataLoader"
base = 65536
language = "ARM:LE:32:v5"
subset = ["base64"]

[dataset.arm32_coreutils_llvm]
path = "./Datasets/coreutils/arm32-llvm"
loader = "ARMCoreutilsDataLoader"
base = 0
language = "ARM:LE:32:v5"
llvm_arm32 = true
subset = ["base64"]

[dataset.mips_coreutils]
path = "./Datasets/coreutils/mips-gcc"
loader = "MIPSCoreutilsDataLoader"
base = 4194304
language = "MIPS:BE:32:default"
subset = ["base64"]

[dataset.mips_coreutils_llvm]
path = "./Datasets/coreutils/mips-llvm"
loader = "MIPSCoreutilsDataLoader"
base = 0
language = "MIPS:BE:32:default"
subset = ["base64"]

[dataset.openssl_x64]
path = "./Datasets/OpenSSL-x64"
loader = "OpensslDataLoader"
base = 0x400000
language = "x86:LE:64:default"
subset = ["openssl_O2"]

[dataset.chromium_pe_x64]
path = "./Datasets/chromium-PE-x64"
loader = "ChromiumDataLoader"
base = 0x140000000
language = "x86:LE:64:default"

[evaluator.nsda]
iteration_limit = 5
epoches_limit = 500
keep_ghidra_prj = false
keep_ghidra_prj_path = "./saved_ghidra_prjs"
legacy = true

[evaluator.nsdaworules]
iteration_limit = 5
epoches_limit = 500
keep_ghidra_prj = false
keep_ghidra_prj_path = "./saved_ghidra_prjs"
legacy = true

[evaluator.probnsda]
iteration_limit = 1
epoches_limit = 2000
keep_ghidra_prj = false
keep_ghidra_prj_path = "./saved_ghidra_prjs"
legacy = true

[evaluator.ghidra]
keep_ghidra_prj = false
keep_ghidra_prj_path = "./saved_ghidra_prjs"
legacy = true

[evaluator.loadstar]
loadstar_home = "./Datasets/Loadstar"
weights_path = "new_weights.weights.h5"
tokenizer_path = "utils/tokenizer.pkl"
maxlen = 100
batch_size = 128
vocab_size = 651997
embedding_dim = 128
lstm_units = 64

[evaluator.ddisasm]

[evaluator.segmentednsda]
iteration_limit = 5
epoches_limit = 500
keep_ghidra_prj_path = "./saved_ghidra_prjs"
function_level = false
segment_size = 1_048_576 # 1MB

# skip_training = true
# project_path = "./saved_ghidra_prjs/20260505_221121_ghidra_project__hcc3mat__segmented_nsda"
# project_name = "chrome"
# file_system_name = "/chrome.dll"